import {
  faArrowRightFromBracket,
  faArrowUp,
  faArrowUpRightFromSquare,
  faBars,
  faBell,
  faBookmark,
  faBuilding,
  faBuildingColumns,
  faCalendar,
  faCheck,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faClockRotateLeft,
  faCircleExclamation,
  faDoorOpen,
  faEllipsis,
  faEllipsisVertical,
  faGear,
  faGift,
  faHeart,
  faHouse,
  faLock,
  faMagnifyingGlass,
  faMinus,
  faMoneyBill1,
  faPaperPlane,
  faPen,
  faPhone,
  faPlus,
  faPrint,
  faStar,
  faThumbtack,
  faTrash,
  faTriangleExclamation,
  faUser,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBell as faBellOutline,
  faBookmark as faBookmarkOutline,
  faBuilding as faBuildingOutline,
  faCalendar as faCalendarOutline,
  faCircleDown,
  faCircleLeft,
  faCircleRight,
  faCircleUp,
  faCircleQuestion as faCircleQuestionOutline,
  faClock as faClockOutline,
  faHeart as faHeartOutline,
  faPaperPlane as faPaperPlaneOutline,
  faStar as faStarOutline,
  faUser as faUserOutline,
} from '@fortawesome/free-regular-svg-icons';
import {
  faFacebook,
  faInstagram,
  faLinkedin,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

export const iconMap: Record<string, IconDefinition> = {
  'arrow-right-from-bracket': faArrowRightFromBracket,
  'arrow-up': faArrowUp,
  'arrow-up-right-from-square': faArrowUpRightFromSquare,
  bars: faBars,
  'bell-outline': faBellOutline,
  bell: faBell,
  'bookmark-outline': faBookmarkOutline,
  bookmark: faBookmark,
  'building-outline': faBuildingOutline,
  building: faBuilding,
  'building-columns': faBuildingColumns,
  'calendar-outline': faCalendarOutline,
  calendar: faCalendar,
  check: faCheck,
  'chevron-down': faCircleDown,
  'chevron-left': faCircleLeft,
  'chevron-right': faCircleRight,
  'chevron-up': faCircleUp,
  circle: faCircle,
  'circle-check': faCircleCheck,
  'circle-info': faCircleInfo,
  'circle-question': faCircleQuestionOutline,
  'clock-outline': faClockOutline,
  'clock-rotate-left': faClockRotateLeft,
  clock: faClock,
  'diamond-exclamation': faCircleExclamation,
  'door-open': faDoorOpen,
  ellipsis: faEllipsis,
  'ellipsis-vertical': faEllipsisVertical,
  'ellipsis-outline': faEllipsis,
  facebook: faFacebook,
  'gear-outline': faGear,
  gear: faGear,
  gift: faGift,
  'gift-outline': faGift,
  'heart-outline': faHeartOutline,
  heart: faHeart,
  'house-outline': faHouse,
  house: faHouse,
  instagram: faInstagram,
  linkedin: faLinkedin,
  'lock-outline': faLock,
  lock: faLock,
  'magnifying-glass': faMagnifyingGlass,
  minus: faMinus,
  'money-bill-wave': faMoneyBill1,
  'paper-plane-outline': faPaperPlaneOutline,
  'paper-plane': faPaperPlane,
  'pen-outline': faPen,
  pen: faPen,
  'phone-outline': faPhone,
  phone: faPhone,
  plus: faPlus,
  'print-outline': faPrint,
  print: faPrint,
  'star-outline': faStarOutline,
  star: faStar,
  'thumbtack-outline': faThumbtack,
  thumbtack: faThumbtack,
  'trash-outline': faTrash,
  trash: faTrash,
  'triangle-exclamation': faTriangleExclamation,
  'user-outline': faUserOutline,
  user: faUser,
  'x-twitter': faTwitter,
  xmark: faXmark,
};
